SELECT PERSON.PERSON_ID, FIRST_NAME, LAST_NAME, STREET, CITY, count(*) as HOW_MANY_ORDERS
FROM PERSON, CLIENT_ORDER
WHERE PERSON.PERSON_ID = CLIENT_ORDER.PERSON_ID
GROUP BY PERSON.PERSON_ID
HAVING HOW_MANY_ORDERS >= 1
ORDER BY HOW_MANY_ORDERS desc;