SELECT P.PERSON_ID, FIRST_NAME, LAST_NAME, STREET, CITY, count(*) as HOW_MANY_ORDERS
FROM PERSON P
INNER JOIN CLIENT_ORDER O
ON P.PERSON_ID = O.PERSON_ID
GROUP BY P.PERSON_ID
HAVING HOW_MANY_ORDERS >= 1
ORDER BY HOW_MANY_ORDERS desc;